/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as CondominiosRouteImport } from './routes/condominios'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as LeilaoRouteImport } from './routes/leilao'
import { Route as NossaHistoriaRouteImport } from './routes/nossa-historia'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as TermosUsoRouteImport } from './routes/termos-uso'
import { Route as AdminOgTesterRouteImport } from './routes/admin/og-tester'
import { Route as CrmLoginRouteImport } from './routes/crm/login'
import { Route as CrmSemAcessoRouteImport } from './routes/crm/sem-acesso'
import { Route as CrmSetupRouteImport } from './routes/crm/setup'
import { Route as ImovelCodigoRouteImport } from './routes/imovel/$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosRoute = CondominiosRouteImport.update({
  id: '/condominios',
  path: '/condominios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const LeilaoRoute = LeilaoRouteImport.update({
  id: '/leilao',
  path: '/leilao',
  getParentRoute: () => rootRouteImport,
} as any)
const NossaHistoriaRoute = NossaHistoriaRouteImport.update({
  id: '/nossa-historia',
  path: '/nossa-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosUsoRoute = TermosUsoRouteImport.update({
  id: '/termos-uso',
  path: '/termos-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOgTesterRoute = AdminOgTesterRouteImport.update({
  id: '/admin/og-tester',
  path: '/admin/og-tester',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLoginRoute = CrmLoginRouteImport.update({
  id: '/crm/login',
  path: '/crm/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSemAcessoRoute = CrmSemAcessoRouteImport.update({
  id: '/crm/sem-acesso',
  path: '/crm/sem-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSetupRoute = CrmSetupRouteImport.update({
  id: '/crm/setup',
  path: '/crm/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelCodigoRoute = ImovelCodigoRouteImport.update({
  id: '/imovel/$codigo',
  path: '/imovel/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/comparar': typeof CompararRoute
  '/condominios': typeof CondominiosRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/leilao': typeof LeilaoRoute
  '/nossa-historia': typeof NossaHistoriaRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/termos-uso': typeof TermosUsoRoute
  '/admin/og-tester': typeof AdminOgTesterRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/sem-acesso': typeof CrmSemAcessoRoute
  '/crm/setup': typeof CrmSetupRoute
  '/imovel/$codigo': typeof ImovelCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/comparar': typeof CompararRoute
  '/condominios': typeof CondominiosRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/leilao': typeof LeilaoRoute
  '/nossa-historia': typeof NossaHistoriaRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/termos-uso': typeof TermosUsoRoute
  '/admin/og-tester': typeof AdminOgTesterRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/sem-acesso': typeof CrmSemAcessoRoute
  '/crm/setup': typeof CrmSetupRoute
  '/imovel/$codigo': typeof ImovelCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/comparar': typeof CompararRoute
  '/condominios': typeof CondominiosRoute
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRoute
  '/leilao': typeof LeilaoRoute
  '/nossa-historia': typeof NossaHistoriaRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/termos-uso': typeof TermosUsoRoute
  '/admin/og-tester': typeof AdminOgTesterRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/sem-acesso': typeof CrmSemAcessoRoute
  '/crm/setup': typeof CrmSetupRoute
  '/imovel/$codigo': typeof ImovelCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avaliacao'
    | '/comparar'
    | '/condominios'
    | '/contato'
    | '/imoveis'
    | '/leilao'
    | '/nossa-historia'
    | '/politica-privacidade'
    | '/termos-uso'
    | '/admin/og-tester'
    | '/crm/login'
    | '/crm/sem-acesso'
    | '/crm/setup'
    | '/imovel/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avaliacao'
    | '/comparar'
    | '/condominios'
    | '/contato'
    | '/imoveis'
    | '/leilao'
    | '/nossa-historia'
    | '/politica-privacidade'
    | '/termos-uso'
    | '/admin/og-tester'
    | '/crm/login'
    | '/crm/sem-acesso'
    | '/crm/setup'
    | '/imovel/$codigo'
  id:
    | '__root__'
    | '/'
    | '/avaliacao'
    | '/comparar'
    | '/condominios'
    | '/contato'
    | '/imoveis'
    | '/leilao'
    | '/nossa-historia'
    | '/politica-privacidade'
    | '/termos-uso'
    | '/admin/og-tester'
    | '/crm/login'
    | '/crm/sem-acesso'
    | '/crm/setup'
    | '/imovel/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  CompararRoute: typeof CompararRoute
  CondominiosRoute: typeof CondominiosRoute
  ContatoRoute: typeof ContatoRoute
  ImoveisRoute: typeof ImoveisRoute
  LeilaoRoute: typeof LeilaoRoute
  NossaHistoriaRoute: typeof NossaHistoriaRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  TermosUsoRoute: typeof TermosUsoRoute
  AdminOgTesterRoute: typeof AdminOgTesterRoute
  CrmLoginRoute: typeof CrmLoginRoute
  CrmSemAcessoRoute: typeof CrmSemAcessoRoute
  CrmSetupRoute: typeof CrmSetupRoute
  ImovelCodigoRoute: typeof ImovelCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios': {
      id: '/condominios'
      path: '/condominios'
      fullPath: '/condominios'
      preLoaderRoute: typeof CondominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leilao': {
      id: '/leilao'
      path: '/leilao'
      fullPath: '/leilao'
      preLoaderRoute: typeof LeilaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nossa-historia': {
      id: '/nossa-historia'
      path: '/nossa-historia'
      fullPath: '/nossa-historia'
      preLoaderRoute: typeof NossaHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-uso': {
      id: '/termos-uso'
      path: '/termos-uso'
      fullPath: '/termos-uso'
      preLoaderRoute: typeof TermosUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/og-tester': {
      id: '/admin/og-tester'
      path: '/admin/og-tester'
      fullPath: '/admin/og-tester'
      preLoaderRoute: typeof AdminOgTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/login': {
      id: '/crm/login'
      path: '/crm/login'
      fullPath: '/crm/login'
      preLoaderRoute: typeof CrmLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/sem-acesso': {
      id: '/crm/sem-acesso'
      path: '/crm/sem-acesso'
      fullPath: '/crm/sem-acesso'
      preLoaderRoute: typeof CrmSemAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/setup': {
      id: '/crm/setup'
      path: '/crm/setup'
      fullPath: '/crm/setup'
      preLoaderRoute: typeof CrmSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$codigo': {
      id: '/imovel/$codigo'
      path: '/imovel/$codigo'
      fullPath: '/imovel/$codigo'
      preLoaderRoute: typeof ImovelCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  CompararRoute: CompararRoute,
  CondominiosRoute: CondominiosRoute,
  ContatoRoute: ContatoRoute,
  ImoveisRoute: ImoveisRoute,
  LeilaoRoute: LeilaoRoute,
  NossaHistoriaRoute: NossaHistoriaRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  TermosUsoRoute: TermosUsoRoute,
  AdminOgTesterRoute: AdminOgTesterRoute,
  CrmLoginRoute: CrmLoginRoute,
  CrmSemAcessoRoute: CrmSemAcessoRoute,
  CrmSetupRoute: CrmSetupRoute,
  ImovelCodigoRoute: ImovelCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
