
ALTER TABLE public.imoveis_proprios
  ADD COLUMN IF NOT EXISTS area_lote numeric,
  ADD COLUMN IF NOT EXISTS area_interna numeric,
  ADD COLUMN IF NOT EXISTS area_privativa numeric,
  ADD COLUMN IF NOT EXISTS area_servico numeric,
  ADD COLUMN IF NOT EXISTS iptu_indice text,
  ADD COLUMN IF NOT EXISTS taxa_administracao_pct numeric,
  ADD COLUMN IF NOT EXISTS taxa_intermediacao_pct numeric,
  ADD COLUMN IF NOT EXISTS seguro_incendio_valor numeric,
  ADD COLUMN IF NOT EXISTS seguro_incendio_parcela numeric,
  ADD COLUMN IF NOT EXISTS administradora text,
  ADD COLUMN IF NOT EXISTS administradora_telefone text,
  ADD COLUMN IF NOT EXISTS administradora_email text,
  ADD COLUMN IF NOT EXISTS sindico text,
  ADD COLUMN IF NOT EXISTS sindico_telefone text,
  ADD COLUMN IF NOT EXISTS sindico_email text,
  ADD COLUMN IF NOT EXISTS data_entrega date,
  ADD COLUMN IF NOT EXISTS data_vago_desde date,
  ADD COLUMN IF NOT EXISTS idade_edificacao text,
  ADD COLUMN IF NOT EXISTS padrao text,
  ADD COLUMN IF NOT EXISTS pontuacao numeric,
  ADD COLUMN IF NOT EXISTS captadores text,
  ADD COLUMN IF NOT EXISTS indicado_por text,
  ADD COLUMN IF NOT EXISTS motivo_desativacao text,
  ADD COLUMN IF NOT EXISTS situacao_imoview text,
  ADD COLUMN IF NOT EXISTS numero_controle text,
  ADD COLUMN IF NOT EXISTS agua_identificador text,
  ADD COLUMN IF NOT EXISTS agua_matricula text,
  ADD COLUMN IF NOT EXISTS luz_numero_cliente text,
  ADD COLUMN IF NOT EXISTS luz_numero_instalacao text,
  ADD COLUMN IF NOT EXISTS portais_publicados jsonb DEFAULT '{}'::jsonb;
