
ALTER TABLE public.imoveis_proprios
  ADD COLUMN IF NOT EXISTS codigo_auxiliar text,
  ADD COLUMN IF NOT EXISTS destinacao text,
  ADD COLUMN IF NOT EXISTS segundo_tipo text,
  ADD COLUMN IF NOT EXISTS local_chaves text,
  ADD COLUMN IF NOT EXISTS identificador_chaves text,
  ADD COLUMN IF NOT EXISTS num_chaves integer,
  ADD COLUMN IF NOT EXISTS num_controles integer,
  ADD COLUMN IF NOT EXISTS horario_visita text,
  ADD COLUMN IF NOT EXISTS edificio text,
  ADD COLUMN IF NOT EXISTS identificador_imovel text,
  ADD COLUMN IF NOT EXISTS etiquetas text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS valor_anterior numeric,
  ADD COLUMN IF NOT EXISTS iptu_anual numeric,
  ADD COLUMN IF NOT EXISTS iptu_mensal numeric,
  ADD COLUMN IF NOT EXISTS rentabilidade_pct numeric,
  ADD COLUMN IF NOT EXISTS comissao_venda_pct numeric,
  ADD COLUMN IF NOT EXISTS valor_sob_consulta boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS valor_avaliacao numeric,
  ADD COLUMN IF NOT EXISTS descricao_avaliacao text,
  ADD COLUMN IF NOT EXISTS exclusivo boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS imovel_ocupado boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS imovel_alugado boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS placa_faixa text,
  ADD COLUMN IF NOT EXISTS cib text,
  ADD COLUMN IF NOT EXISTS aceita_financiamento boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS na_planta boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS permite_animais boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS area_externa numeric,
  ADD COLUMN IF NOT EXISTS tipo_medida text,
  ADD COLUMN IF NOT EXISTS m_frente numeric,
  ADD COLUMN IF NOT EXISTS m_fundo numeric,
  ADD COLUMN IF NOT EXISTS m_direito numeric,
  ADD COLUMN IF NOT EXISTS m_esquerdo numeric,
  ADD COLUMN IF NOT EXISTS confront_frente text,
  ADD COLUMN IF NOT EXISTS confront_fundo text,
  ADD COLUMN IF NOT EXISTS confront_dir text,
  ADD COLUMN IF NOT EXISTS confront_esq text,
  ADD COLUMN IF NOT EXISTS zona_uso text,
  ADD COLUMN IF NOT EXISTS coef_aproveitamento numeric,
  ADD COLUMN IF NOT EXISTS ponto_referencia text,
  ADD COLUMN IF NOT EXISTS melhor_acesso text,
  ADD COLUMN IF NOT EXISTS titulo_anuncio text,
  ADD COLUMN IF NOT EXISTS meta_description text,
  ADD COLUMN IF NOT EXISTS construtora text,
  ADD COLUMN IF NOT EXISTS ano_construcao integer,
  ADD COLUMN IF NOT EXISTS venc_autorizacao_venda date,
  ADD COLUMN IF NOT EXISTS cartorio text,
  ADD COLUMN IF NOT EXISTS matricula text,
  ADD COLUMN IF NOT EXISTS livro_cartorio text,
  ADD COLUMN IF NOT EXISTS folha_cartorio text,
  ADD COLUMN IF NOT EXISTS andar text,
  ADD COLUMN IF NOT EXISTS piso_acabamento text,
  ADD COLUMN IF NOT EXISTS posicao_imovel text,
  ADD COLUMN IF NOT EXISTS salas integer,
  ADD COLUMN IF NOT EXISTS varandas integer,
  ADD COLUMN IF NOT EXISTS tipo_vaga text,
  ADD COLUMN IF NOT EXISTS elevadores integer,
  ADD COLUMN IF NOT EXISTS num_torres integer,
  ADD COLUMN IF NOT EXISTS num_andares integer,
  ADD COLUMN IF NOT EXISTS unidades_por_andar integer,
  ADD COLUMN IF NOT EXISTS total_unidades integer,
  ADD COLUMN IF NOT EXISTS sub_regiao text,
  ADD COLUMN IF NOT EXISTS regiao text,
  ADD COLUMN IF NOT EXISTS numero text,
  ADD COLUMN IF NOT EXISTS complemento text,
  ADD COLUMN IF NOT EXISTS tipo_complemento text,
  ADD COLUMN IF NOT EXISTS torre_bloco text,
  ADD COLUMN IF NOT EXISTS segundo_bairro text,
  ADD COLUMN IF NOT EXISTS observacoes_internas text,
  ADD COLUMN IF NOT EXISTS notas_privadas text;
